name: Lookup
author : Pasindu Perera
description : SMS based directory for organizations in Sri Lanka.
url : http://lookup.ideawide.com
image : http://lookup.ideawide.com/img/home.png
markdown: redcarpet
pygments: true
